### ISSUE TITLE
jvm-Redux collective

### ISSUE THREAD

**Issue by glung** [beyondeye/Reduks#16]
Hello, I could not find a better way to contact you. Sorry :/

Because you worked on Redux for the JVM, I've been thinking you may be interested in joining the collective we are starting on that subject. We would like to explore it more and see how far we can go. 

If you want to join, please follow the link ->
https://docs.google.com/document/d/13jdWEI1Jqs5GHO0pG6qMloOEQdph9If-tj9P1I3VHDA/edit?usp=sharing

Best

**Comment by beyondeye** [comment]
The idea of a team is a very good one. Fragmentation is bad. On the other hand I think there is a need for more discussion about the goals. Also, since one of the goal is idiomatic usage in kotlin,what about moving the discussion in a new ad hoc channel in kotlin slack?

**Comment by glung** [comment]
Hey, thank you. I will shortly follow up and we can discuss all of your
points. (You don't have to commit to anything obsly :)

**Comment by glung** [comment]
Hello, here is the discussion group. I think the RFC on the mission statement address your comment but it would be great to have your feedback on it (really just 3 minutes to read it). https://groups.google.com/forum/#!forum/jvm-redux
