### ISSUE TITLE
Reduce method count in reduks core

### ISSUE THREAD

**Issue by beyondeye** [beyondeye/Reduks#2]
After adding support for modules, method count in reduks core has increased to significantly (the module package has now 524 method). Need to find a way to reduce it. Using data classes for module def was a bad idea probably, because it adds tons of methods I don't actually need. See attached full list of methods
[core_method_list.txt](https://github.com/beyondeye/Reduks/files/406185/core_method_list.txt)

**Comment by kittinunf** [comment]
One alternative to solve this is to again split the module out from core. This would make core as bare-minimum as possible.

**Comment by beyondeye** [comment]
Yes, I would probably do it

**Comment by beyondeye** [comment]
Update method list of core, after optimizations with jvmfield and data class removal [reduks_core_method_list_b3.txt](https://github.com/beyondeye/Reduks/files/409209/reduks_core_method_list_b3.txt)

**Comment by beyondeye** [comment]
After all optimizations, now method count in reduks-core is acceptable (around 430 methods)
